name: Affluence
version: 1.0
main: com.coariz.affluence.Affluence
api-version: 1.21
authors:
  - Coariz
description: Affluence Plugin for Minecraft Server
commands:
  affluence:
    description: Affluence plugin command
    usage: /<command> <subcommand>
    aliases:
      - aff
    permission: affluence.use
    permission-message: "&cYou don't have permission to do that!"
    subcommands:
      reload:
        description: Reloads the Affluence configuration
        usage: /affluence reload
        permission: affluence.admin
        permission-message: "&cYou don't have permission to reload the configuration!"
      set:
        description: Sets a configuration value
        usage: /affluence set <path> <value>
        permission: affluence.admin
        permission-message: "&cYou don't have permission to set configuration values!"
      balance:
        description: Shows your Affluence balance
        usage: /affluence balance
        aliases:
          - bal
        permission: affluence.use
        permission-message: "&cYou don't have permission to check your balance!"
      deposit:
        description: Deposits money from your Vault balance to your Affluence balance
        usage: /affluence deposit <amount>
        aliases:
          - dep
        permission: affluence.use
        permission-message: "&cYou don't have permission to deposit money!"
      withdraw:
        description: Withdraws money from your Affluence balance to your Vault balance
        usage: /affluence withdraw <amount>
        aliases:
          - with
        permission: affluence.use
        permission-message: "&cYou don't have permission to withdraw money!"
permissions:
  affluence.use:
    description: Allows players to use the Affluence plugin commands
    default: true
  affluence.admin:
    description: Allows reloading the affluence configuration and setting configuration values
    default: op