name: CoarizWildTP
version: 1.2
main: com.coariz.coarizwildtp.CoarizWildTP
api-version: 1.21
commands:
  wild:
    description: Teleports you to a random safe location.
    aliases:
      - rtp
  coarizwildtp:
    description: Manages CoarizWildTP plugin commands.
    usage: /<command> <subcommand>
permissions:
  coarizwildtp.use:
    description: Allows the player to use the /wild command.
    default: op
  coarizwildtp.bypasscooldown:
    description: Allows the player to bypass the teleportation cooldown.
    default: op
  coarizwildtp.reload:
    description: Allows the admin to reload the plugin configuration.
    default: op
